name: 'mapspike'
version: 0.0.1
description: >
  A pure dart proof of concept agent-based model.
author: Ernesto Carrella <ernesto.carrella@gmail.com>
homepage: carrknight.github.io
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  google_maps: any
dev_dependencies:
  unittest: any
  darwin: ">=0.2.4 <0.3.0"

